name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildandtest:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run default tests
        run: cargo test --verbose
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack --version
      - name: Run headless browser tests
        run: |
          wasm-pack test --headless --chrome
          wasm-pack test --headless --firefox

  readme:
    name: Build readme
    runs-on: ubuntu-latest
    needs: buildandtest

    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-readme
        run: cargo install cargo-readme
      - name: Create README.md file from src/lib.rs
        run: cargo readme -i src/lib.rs -o README.md
